<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>..\..\..\bin\Content.Server\</OutputPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <OutputType Condition="'$(FullRelease)' != 'True'">Exe</OutputType>
    <NoWarn>1998</NoWarn>
    <WarningsAsErrors>nullable</WarningsAsErrors>
    <Nullable>enable</Nullable>
    <ServerGarbageCollection>true</ServerGarbageCollection>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Content.Server\Content.Server.csproj" />
    <ProjectReference Include="..\Content.Lavaland.Common\Content.Lavaland.Common.csproj" />
    <ProjectReference Include="..\Content.Lavaland.Shared\Content.Lavaland.Shared.csproj" />
  </ItemGroup>

</Project>
