// <auto-generated />
using System;
using Content.Server.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Content.Server.Database.Migrations.Sqlite
{
    [DbContext(typeof(SqliteServerDbContext))]
    [Migration("20260829095540_MoveToWizdenDB")]
    partial class MoveToWizdenDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("Content.Server.Database.Admin", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("AdminRankId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deadminned")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Suspended")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("AdminRankId");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("Content.Server.Database.AdminFlag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Flag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Negative")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("Flag", "AdminId")
                        .IsUnique();

                    b.ToTable("AdminFlag");
                });

            modelBuilder.Entity("Content.Server.Database.AdminLog", b =>
                {
                    b.Property<int>("RoundId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<sbyte>("Impact")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoundId", "Id");

                    b.HasIndex("Date");

                    b.HasIndex("Type");

                    b.ToTable("AdminLog");
                });

            modelBuilder.Entity("Content.Server.Database.AdminLogPlayer", b =>
                {
                    b.Property<int>("RoundId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LogId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlayerUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("RoundId", "LogId", "PlayerUserId");

                    b.HasIndex("PlayerUserId");

                    b.ToTable("AdminLogPlayer");
                });

            modelBuilder.Entity("Content.Server.Database.AdminMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Dismissed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastEditedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LastEditedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PlayerUserId")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("PlaytimeAtNote")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoundId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Seen")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("LastEditedById");

                    b.HasIndex("PlayerUserId");

                    b.HasIndex("RoundId");

                    b.ToTable("AdminMessages", t =>
                        {
                            t.HasCheckConstraint("NotDismissedAndSeen", "NOT dismissed OR seen");
                        });
                });

            modelBuilder.Entity("Content.Server.Database.AdminNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastEditedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LastEditedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PlayerUserId")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("PlaytimeAtNote")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoundId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Secret")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("LastEditedById");

                    b.HasIndex("PlayerUserId");

                    b.HasIndex("RoundId");

                    b.ToTable("AdminNotes");
                });

            modelBuilder.Entity("Content.Server.Database.AdminRank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AdminRank");
                });

            modelBuilder.Entity("Content.Server.Database.AdminRankFlag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdminRankId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Flag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdminRankId");

                    b.HasIndex("Flag", "AdminRankId")
                        .IsUnique();

                    b.ToTable("AdminRankFlag");
                });

            modelBuilder.Entity("Content.Server.Database.AdminWatchlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastEditedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LastEditedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PlayerUserId")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("PlaytimeAtNote")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoundId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("LastEditedById");

                    b.HasIndex("PlayerUserId");

                    b.HasIndex("RoundId");

                    b.ToTable("AdminWatchlists");
                });

            modelBuilder.Entity("Content.Server.Database.Antag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AntagName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "AntagName")
                        .IsUnique();

                    b.ToTable("Antag");
                });

            modelBuilder.Entity("Content.Server.Database.AssignedUserId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("AssignedUserId");
                });

            modelBuilder.Entity("Content.Server.Database.Ban", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoDelete")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BanTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BanningAdmin")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExemptFlags")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Hidden")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastEditedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LastEditedById")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("PlaytimeAtNote")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BanningAdmin");

                    b.HasIndex("LastEditedById");

                    b.ToTable("Ban", t =>
                        {
                            t.HasCheckConstraint("NoExemptOnRoleBan", "type = 0 OR exempt_flags = 0");
                        });
                });

            modelBuilder.Entity("Content.Server.Database.BanAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BanId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BanId");

                    b.ToTable("BanAddress");
                });

            modelBuilder.Entity("Content.Server.Database.BanHwid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BanId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BanId");

                    b.ToTable("BanHwid");
                });

            modelBuilder.Entity("Content.Server.Database.BanPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BanId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BanId");

                    b.HasIndex("UserId", "BanId")
                        .IsUnique();

                    b.ToTable("BanPlayer");
                });

            modelBuilder.Entity("Content.Server.Database.BanRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BanId");

                    b.HasIndex("RoleType", "RoleId", "BanId")
                        .IsUnique();

                    b.ToTable("BanRole");
                });

            modelBuilder.Entity("Content.Server.Database.BanRound", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BanId");

                    b.HasIndex("RoundId", "BanId")
                        .IsUnique();

                    b.ToTable("BanRound");
                });

            modelBuilder.Entity("Content.Server.Database.BanTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoDelete")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExemptFlags")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Hidden")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Length")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BanTemplate");
                });

            modelBuilder.Entity("Content.Server.Database.Blacklist", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("blacklist");
                });

            modelBuilder.Entity("Content.Server.Database.ConnectionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte?>("Denied")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.Property<float>("Trust")
                        .HasColumnType("REAL");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.HasIndex("Time");

                    b.HasIndex("UserId");

                    b.ToTable("connection_log");
                });

            modelBuilder.Entity("Content.Server.Database.CustomVoteLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoundId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("State")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InitiatorId");

                    b.HasIndex("RoundId");

                    b.ToTable("CustomVoteLog");
                });

            modelBuilder.Entity("Content.Server.Database.CustomVoteLogOption", b =>
                {
                    b.Property<int>("VoteId")
                        .HasColumnType("INTEGER");

                    b.Property<short>("OptionIdx")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VoteCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("VoteId", "OptionIdx");

                    b.ToTable("CustomVoteLogOption");
                });

            modelBuilder.Entity("Content.Server.Database.IPIntelCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Score")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique();

                    b.ToTable("IPIntelCache");
                });

            modelBuilder.Entity("Content.Server.Database.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("ProfileId", "JobName")
                        .IsUnique();

                    b.HasIndex(new[] { "ProfileId" }, "IX_job_one_high_priority")
                        .IsUnique()
                        .HasFilter("priority = 3");

                    b.ToTable("Job");
                });

            modelBuilder.Entity("Content.Server.Database.PlayTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("TimeSpent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tracker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "Tracker")
                        .IsUnique();

                    b.ToTable("play_time");
                });

            modelBuilder.Entity("Content.Server.Database.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FirstSeenTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastReadRules")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSeenAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSeenUserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastSeenUserName");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("player");
                });

            modelBuilder.Entity("Content.Server.Database.Preference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdminOOCColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("ConstructionFavorites")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SelectedCharacterSlot")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Preference");
                });

            modelBuilder.Entity("Content.Server.Database.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("char_name");

                    b.Property<string>("EyeColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FacialHairColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FacialHairName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlavorText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HairColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HairName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Markings")
                        .HasColumnType("jsonb");

                    b.Property<byte[]>("OrganMarkings")
                        .HasColumnType("jsonb");

                    b.Property<int>("PreferenceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreferenceUnavailable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pref_unavailable");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SkinColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Slot")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpawnPriority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Voice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PreferenceId");

                    b.HasIndex("Slot", "PreferenceId")
                        .IsUnique();

                    b.ToTable("Profile");
                });

            modelBuilder.Entity("Content.Server.Database.ProfileLoadout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoadoutName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfileLoadoutGroupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileLoadoutGroupId");

                    b.ToTable("ProfileLoadout");
                });

            modelBuilder.Entity("Content.Server.Database.ProfileLoadoutGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfileRoleLoadoutId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileRoleLoadoutId");

                    b.ToTable("ProfileLoadoutGroup");
                });

            modelBuilder.Entity("Content.Server.Database.ProfileRoleLoadout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("ProfileRoleLoadout");
                });

            modelBuilder.Entity("Content.Server.Database.RoleWhitelist", b =>
                {
                    b.Property<Guid>("PlayerUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("PlayerUserId", "RoleId");

                    b.ToTable("RoleWhitelists");
                });

            modelBuilder.Entity("Content.Server.Database.Round", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.HasIndex("StartDate");

                    b.ToTable("Round");
                });

            modelBuilder.Entity("Content.Server.Database.Server", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Server");
                });

            modelBuilder.Entity("Content.Server.Database.ServerBanExemption", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Flags")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.ToTable("server_ban_exemption", t =>
                        {
                            t.HasCheckConstraint("FlagsNotZero", "flags != 0");
                        });
                });

            modelBuilder.Entity("Content.Server.Database.ServerBanHit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConnectionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BanId");

                    b.HasIndex("ConnectionId");

                    b.ToTable("ServerBanHit");
                });

            modelBuilder.Entity("Content.Server.Database.Trait", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TraitName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "TraitName")
                        .IsUnique();

                    b.ToTable("Trait");
                });

            modelBuilder.Entity("Content.Server.Database.Unban", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BanId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UnbanTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UnbanningAdmin")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BanId")
                        .IsUnique();

                    b.ToTable("Unban");
                });

            modelBuilder.Entity("Content.Server.Database.UploadedResourceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("uploaded_resource_log");
                });

            modelBuilder.Entity("Content.Server.Database.Whitelist", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("whitelist");
                });

            modelBuilder.Entity("PlayerRound", b =>
            {
                b.Property<int>("PlayersId")
                    .HasColumnType("INTEGER")
                    .HasColumnName("players_id");

                b.Property<int>("RoundsId")
                    .HasColumnType("INTEGER")
                    .HasColumnName("rounds_id");

                b.HasKey("PlayersId", "RoundsId");

                b.HasIndex("RoundsId");

                b.ToTable("player_round");
            });

            modelBuilder.Entity("Content.Server.Database.Admin", b =>
                {
                    b.HasOne("Content.Server.Database.AdminRank", "AdminRank")
                        .WithMany("Admins")
                        .HasForeignKey("AdminRankId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AdminRank");
                });

            modelBuilder.Entity("Content.Server.Database.AdminFlag", b =>
                {
                    b.HasOne("Content.Server.Database.Admin", "Admin")
                        .WithMany("Flags")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("Content.Server.Database.AdminLog", b =>
                {
                    b.HasOne("Content.Server.Database.Round", "Round")
                        .WithMany("AdminLogs")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Round");
                });

            modelBuilder.Entity("Content.Server.Database.AdminLogPlayer", b =>
                {
                    b.HasOne("Content.Server.Database.Player", "Player")
                        .WithMany("AdminLogs")
                        .HasForeignKey("PlayerUserId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Content.Server.Database.AdminLog", "Log")
                        .WithMany("Players")
                        .HasForeignKey("RoundId", "LogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Log");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Content.Server.Database.AdminMessage", b =>
                {
                    b.HasOne("Content.Server.Database.Player", "CreatedBy")
                        .WithMany("AdminMessagesCreated")
                        .HasForeignKey("CreatedById")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Content.Server.Database.Player", "DeletedBy")
                        .WithMany("AdminMessagesDeleted")
                        .HasForeignKey("DeletedById")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Content.Server.Database.Player", "LastEditedBy")
                        .WithMany("AdminMessagesLastEdited")
                        .HasForeignKey("LastEditedById")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Content.Server.Database.Player", "Player")
                        .WithMany("AdminMessagesReceived")
                        .HasForeignKey("PlayerUserId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Content.Server.Database.Round", "Round")
                        .WithMany()
                        .HasForeignKey("RoundId");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("LastEditedBy");

                    b.Navigation("Player");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("Content.Server.Database.AdminNote", b =>
                {
                    b.HasOne("Content.Server.Database.Player", "CreatedBy")
                        .WithMany("AdminNotesCreated")
                        .HasForeignKey("CreatedById")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Content.Server.Database.Player", "DeletedBy")
                        .WithMany("AdminNotesDeleted")
                        .HasForeignKey("DeletedById")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Content.Server.Database.Player", "LastEditedBy")
                        .WithMany("AdminNotesLastEdited")
                        .HasForeignKey("LastEditedById")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Content.Server.Database.Player", "Player")
                        .WithMany("AdminNotesReceived")
                        .HasForeignKey("PlayerUserId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Content.Server.Database.Round", "Round")
                        .WithMany()
                        .HasForeignKey("RoundId");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("LastEditedBy");

                    b.Navigation("Player");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("Content.Server.Database.AdminRankFlag", b =>
                {
                    b.HasOne("Content.Server.Database.AdminRank", "Rank")
                        .WithMany("Flags")
                        .HasForeignKey("AdminRankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rank");
                });

            modelBuilder.Entity("Content.Server.Database.AdminWatchlist", b =>
                {
                    b.HasOne("Content.Server.Database.Player", "CreatedBy")
                        .WithMany("AdminWatchlistsCreated")
                        .HasForeignKey("CreatedById")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Content.Server.Database.Player", "DeletedBy")
                        .WithMany("AdminWatchlistsDeleted")
                        .HasForeignKey("DeletedById")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Content.Server.Database.Player", "LastEditedBy")
                        .WithMany("AdminWatchlistsLastEdited")
                        .HasForeignKey("LastEditedById")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Content.Server.Database.Player", "Player")
                        .WithMany("AdminWatchlistsReceived")
                        .HasForeignKey("PlayerUserId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Content.Server.Database.Round", "Round")
                        .WithMany()
                        .HasForeignKey("RoundId");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("LastEditedBy");

                    b.Navigation("Player");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("Content.Server.Database.Antag", b =>
                {
                    b.HasOne("Content.Server.Database.Profile", "Profile")
                        .WithMany("Antags")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Content.Server.Database.Ban", b =>
                {
                    b.HasOne("Content.Server.Database.Player", "CreatedBy")
                        .WithMany("AdminServerBansCreated")
                        .HasForeignKey("BanningAdmin")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Content.Server.Database.Player", "LastEditedBy")
                        .WithMany("AdminServerBansLastEdited")
                        .HasForeignKey("LastEditedById")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");

                    b.Navigation("LastEditedBy");
                });

            modelBuilder.Entity("Content.Server.Database.BanAddress", b =>
                {
                    b.HasOne("Content.Server.Database.Ban", "Ban")
                        .WithMany("Addresses")
                        .HasForeignKey("BanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ban");
                });

            modelBuilder.Entity("Content.Server.Database.BanHwid", b =>
                {
                    b.HasOne("Content.Server.Database.Ban", "Ban")
                        .WithMany("Hwids")
                        .HasForeignKey("BanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Content.Server.Database.TypedHwid", "HWId", b1 =>
                        {
                            b1.Property<int>("BanHwidId")
                                .HasColumnType("INTEGER");

                            b1.Property<byte[]>("Hwid")
                                .IsRequired()
                                .HasColumnType("BLOB")
                                .HasColumnName("hwid");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.HasKey("BanHwidId");

                            b1.ToTable("BanHwid");

                            b1.WithOwner()
                                .HasForeignKey("BanHwidId");
                        });

                    b.Navigation("Ban");

                    b.Navigation("HWId")
                        .IsRequired();
                });

            modelBuilder.Entity("Content.Server.Database.BanPlayer", b =>
                {
                    b.HasOne("Content.Server.Database.Ban", "Ban")
                        .WithMany("Players")
                        .HasForeignKey("BanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ban");
                });

            modelBuilder.Entity("Content.Server.Database.BanRole", b =>
                {
                    b.HasOne("Content.Server.Database.Ban", "Ban")
                        .WithMany("Roles")
                        .HasForeignKey("BanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ban");
                });

            modelBuilder.Entity("Content.Server.Database.BanRound", b =>
                {
                    b.HasOne("Content.Server.Database.Ban", "Ban")
                        .WithMany("Rounds")
                        .HasForeignKey("BanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Content.Server.Database.Round", "Round")
                        .WithMany()
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ban");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("Content.Server.Database.ConnectionLog", b =>
                {
                    b.HasOne("Content.Server.Database.Server", "Server")
                        .WithMany("ConnectionLogs")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.OwnsOne("Content.Server.Database.TypedHwid", "HWId", b1 =>
                        {
                            b1.Property<int>("ConnectionLogId")
                                .HasColumnType("INTEGER");

                            b1.Property<byte[]>("Hwid")
                                .IsRequired()
                                .HasColumnType("BLOB")
                                .HasColumnName("hwid");

                            b1.Property<int>("Type")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER")
                                .HasDefaultValue(0);

                            b1.HasKey("ConnectionLogId");

                            b1.ToTable("connection_log");

                            b1.WithOwner()
                                .HasForeignKey("ConnectionLogId");
                        });

                    b.Navigation("HWId");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("Content.Server.Database.CustomVoteLog", b =>
                {
                    b.HasOne("Content.Server.Database.Player", "Initiator")
                        .WithMany()
                        .HasForeignKey("InitiatorId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Content.Server.Database.Round", "Round")
                        .WithMany("CustomVoteLogs")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Initiator");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("Content.Server.Database.CustomVoteLogOption", b =>
                {
                    b.HasOne("Content.Server.Database.CustomVoteLog", "Vote")
                        .WithMany("Options")
                        .HasForeignKey("VoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vote");
                });

            modelBuilder.Entity("Content.Server.Database.Job", b =>
                {
                    b.HasOne("Content.Server.Database.Profile", "Profile")
                        .WithMany("Jobs")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Content.Server.Database.Player", b =>
                {
                    b.OwnsOne("Content.Server.Database.TypedHwid", "LastSeenHWId", b1 =>
                        {
                            b1.Property<int>("PlayerId")
                                .HasColumnType("INTEGER");

                            b1.Property<byte[]>("Hwid")
                                .IsRequired()
                                .HasColumnType("BLOB")
                                .HasColumnName("last_seen_hwid");

                            b1.Property<int>("Type")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER")
                                .HasDefaultValue(0);

                            b1.HasKey("PlayerId");

                            b1.ToTable("player");

                            b1.WithOwner()
                                .HasForeignKey("PlayerId");
                        });

                    b.Navigation("LastSeenHWId");
                });

            modelBuilder.Entity("Content.Server.Database.Profile", b =>
                {
                    b.HasOne("Content.Server.Database.Preference", "Preference")
                        .WithMany("Profiles")
                        .HasForeignKey("PreferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Preference");
                });

            modelBuilder.Entity("Content.Server.Database.ProfileLoadout", b =>
                {
                    b.HasOne("Content.Server.Database.ProfileLoadoutGroup", "ProfileLoadoutGroup")
                        .WithMany("Loadouts")
                        .HasForeignKey("ProfileLoadoutGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProfileLoadoutGroup");
                });

            modelBuilder.Entity("Content.Server.Database.ProfileLoadoutGroup", b =>
                {
                    b.HasOne("Content.Server.Database.ProfileRoleLoadout", "ProfileRoleLoadout")
                        .WithMany("Groups")
                        .HasForeignKey("ProfileRoleLoadoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProfileRoleLoadout");
                });

            modelBuilder.Entity("Content.Server.Database.ProfileRoleLoadout", b =>
                {
                    b.HasOne("Content.Server.Database.Profile", "Profile")
                        .WithMany("Loadouts")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Content.Server.Database.RoleWhitelist", b =>
                {
                    b.HasOne("Content.Server.Database.Player", "Player")
                        .WithMany("JobWhitelists")
                        .HasForeignKey("PlayerUserId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Content.Server.Database.Round", b =>
                {
                    b.HasOne("Content.Server.Database.Server", "Server")
                        .WithMany("Rounds")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("Content.Server.Database.ServerBanHit", b =>
                {
                    b.HasOne("Content.Server.Database.Ban", "Ban")
                        .WithMany("BanHits")
                        .HasForeignKey("BanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Content.Server.Database.ConnectionLog", "Connection")
                        .WithMany("BanHits")
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ban");

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("Content.Server.Database.Trait", b =>
                {
                    b.HasOne("Content.Server.Database.Profile", "Profile")
                        .WithMany("Traits")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Content.Server.Database.Unban", b =>
                {
                    b.HasOne("Content.Server.Database.Ban", "Ban")
                        .WithOne("Unban")
                        .HasForeignKey("Content.Server.Database.Unban", "BanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ban");
                });

            modelBuilder.Entity("PlayerRound", b =>
                {
                    b.HasOne("Content.Server.Database.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Content.Server.Database.Round", null)
                        .WithMany()
                        .HasForeignKey("RoundsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Content.Server.Database.Admin", b =>
                {
                    b.Navigation("Flags");
                });

            modelBuilder.Entity("Content.Server.Database.AdminLog", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("Content.Server.Database.AdminRank", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("Flags");
                });

            modelBuilder.Entity("Content.Server.Database.Ban", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("BanHits");

                    b.Navigation("Hwids");

                    b.Navigation("Players");

                    b.Navigation("Roles");

                    b.Navigation("Rounds");

                    b.Navigation("Unban");
                });

            modelBuilder.Entity("Content.Server.Database.ConnectionLog", b =>
                {
                    b.Navigation("BanHits");
                });

            modelBuilder.Entity("Content.Server.Database.CustomVoteLog", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("Content.Server.Database.Player", b =>
                {
                    b.Navigation("AdminLogs");

                    b.Navigation("AdminMessagesCreated");

                    b.Navigation("AdminMessagesDeleted");

                    b.Navigation("AdminMessagesLastEdited");

                    b.Navigation("AdminMessagesReceived");

                    b.Navigation("AdminNotesCreated");

                    b.Navigation("AdminNotesDeleted");

                    b.Navigation("AdminNotesLastEdited");

                    b.Navigation("AdminNotesReceived");

                    b.Navigation("AdminServerBansCreated");

                    b.Navigation("AdminServerBansLastEdited");

                    b.Navigation("AdminWatchlistsCreated");

                    b.Navigation("AdminWatchlistsDeleted");

                    b.Navigation("AdminWatchlistsLastEdited");

                    b.Navigation("AdminWatchlistsReceived");

                    b.Navigation("JobWhitelists");
                });

            modelBuilder.Entity("Content.Server.Database.Preference", b =>
                {
                    b.Navigation("Profiles");
                });

            modelBuilder.Entity("Content.Server.Database.Profile", b =>
                {
                    b.Navigation("Antags");

                    b.Navigation("Jobs");

                    b.Navigation("Loadouts");

                    b.Navigation("Traits");
                });

            modelBuilder.Entity("Content.Server.Database.ProfileLoadoutGroup", b =>
                {
                    b.Navigation("Loadouts");
                });

            modelBuilder.Entity("Content.Server.Database.ProfileRoleLoadout", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("Content.Server.Database.Round", b =>
                {
                    b.Navigation("AdminLogs");

                    b.Navigation("CustomVoteLogs");
                });

            modelBuilder.Entity("Content.Server.Database.Server", b =>
                {
                    b.Navigation("ConnectionLogs");

                    b.Navigation("Rounds");
                });
#pragma warning restore 612, 618
        }
    }
}
