// SPDX-FileCopyrightText: 2026 Goob Station Contributors
//
// SPDX-License-Identifier: MPL-2.0

using Content.Goobstation.Shared.Supermatter.Systems;
using Content.Shared.Atmos;
using Content.Shared.DoAfter;
using Content.Shared.Whitelist;
using Robust.Shared.Audio;
using Robust.Shared.GameStates;
using Robust.Shared.Prototypes;
using Robust.Shared.Serialization;
using Robust.Shared.Serialization.TypeSerializers.Implementations.Custom.Prototype;
using Robust.Shared.Serialization.TypeSerializers.Implementations.Custom.Prototype.Array;

namespace Content.Goobstation.Shared.Supermatter.Components;

[RegisterComponent, NetworkedComponent]
public sealed partial class SupermatterComponent : Component
{
    #region SM Base

    /// <summary>
    ///     The SM will only cycle if activated.
    /// </summary>
    [DataField("activated")]
    public bool Activated = false;

    [DataField("supermatterSliverPrototype", customTypeSerializer: typeof(PrototypeIdSerializer<EntityPrototype>))]
    public string SliverPrototypeId { get; private set; } = "SupermatterSliver";

    /// <summary>
    ///     Affects delamination timer. If removed - delamination timer is divided by 2.
    /// </summary>
    [DataField("sliverRemoved")]
    public bool SliverRemoved = false;

    /// <summary>
    /// What will be spawned when an entity that's not supermatter immune interacts with it.
    /// </summary>
    [DataField("ashPrototype", customTypeSerializer: typeof(PrototypeIdSerializer<EntityPrototype>))]
    public string AshPrototypeId { get; private set; } = "Ash";

    /// <summary>
    /// There has to be a way to serialize this properly
    /// </summary>
    public readonly string[] LightningPrototypes =
    [
        "Lightning",
        "ChargedLightning",
        "SuperchargedLightning",
        "HyperchargedLightning"
    ];

    [DataField("singularitySpawnPrototype", customTypeSerializer: typeof(PrototypeIdSerializer<EntityPrototype>))]
    public string SingularityPrototypeId = "Singularity";

    [DataField("teslaSpawnPrototype", customTypeSerializer: typeof(PrototypeIdSerializer<EntityPrototype>))]
    public string TeslaPrototypeId = "TeslaEnergyBall";

    [DataField("supermatterKudzuSpawnPrototype", customTypeSerializer: typeof(PrototypeIdSerializer<EntityPrototype>))]
    public string SupermatterKudzuPrototypeId = "SupermatterKudzu";

    /// <summary>
    /// This is what you're here for
    /// </summary>
    [ViewVariables(VVAccess.ReadWrite)]
    public float Power;

    /// <summary>
    /// The amount of damage we have currently
    /// </summary>
    [ViewVariables(VVAccess.ReadWrite)]
    public float Damage = 0f;

    /// <summary>
    /// Damage change since last cycle
    /// </summary>
    [ViewVariables(VVAccess.ReadWrite)]
    public float DamageDelta = 0f;

    /// <summary>
    /// Temporary power gained from mob consumption. Purely to not instaspike power to 2000 or something.
    /// </summary>
    [ViewVariables(VVAccess.ReadWrite)]
    public float MatterPower;

    /// <summary>
    /// Ratio of matter power to power conversion rate. 1 mob = 10 matter power
    /// </summary>
    [ViewVariables(VVAccess.ReadWrite)]
    public float MatterPowerConversion = 1f;

    /// <summary>
    /// The portion of the gasmix we're on. Relevant for gas processing but not for plain checks.
    /// </summary>
    [ViewVariables(VVAccess.ReadWrite)]
    public float GasEfficiency = 0.15f;

    /// <summary>
    /// Multiply outgoing rads by this. Generic knob.
    /// </summary>
    [DataField("radiationOutputFactor")]
    [ViewVariables(VVAccess.ReadWrite)]
    public float RadiationOutputFactor = 1f;

    #endregion SM Base

    #region SM Sound
    /// <summary>
    /// Current stream of SM audio.
    /// </summary>
    public EntityUid? AudioStream;

    public SharedSupermatterSystem.SuperMatterSound? SmSound;

    [DataField("dustSound")]
    public SoundSpecifier DustSound = new SoundPathSpecifier("/Audio/Supermatter/dust.ogg");

    [DataField("delamSound")]
    public SoundSpecifier DelamSound = new SoundPathSpecifier("/Audio/Supermatter/delamming.ogg");

    [DataField("delamAlarm")]
    public SoundSpecifier DelamAlarm = new SoundPathSpecifier("/Audio/Machines/alarm.ogg");

    #endregion SM Sound

    #region SM Calculation

    /// <summary>
    /// Based on co2 percentage, slowly moves between
    /// 0 and 1. We use it to calc the powerloss_inhibitor
    /// </summary>
    [ViewVariables(VVAccess.ReadOnly)]
    public float PowerlossDynamicScaling;

    /// <summary>
    /// Multiplier on damage the core takes from absorbing hot gas
    /// Default is ~1/350
    /// </summary>
    [ViewVariables(VVAccess.ReadOnly)]
    public float MoleHeatPenalty = 0.00286f;

    /// <summary>
    /// Inverse of MoleHeatPenalty
    /// </summary>
    [ViewVariables(VVAccess.ReadOnly)]
    public float MoleHeatThreshold = 350f;

    /// <summary>
    /// Multiplier on power generated by nuclear reactions
    /// </summary>
    [ViewVariables(VVAccess.ReadOnly)]
    [DataField("reactionpowerModifier")]
    public float ReactionPowerModifier = 0.55f;

    /// <summary>
    /// Acts as a multiplier on the amount that nuclear reactions increase the supermatter core temperature
    /// </summary>
    [ViewVariables(VVAccess.ReadWrite)]
    [DataField("thermalreleaseModifier")]
    public float ThermalReleaseModifier = 0.2f;

    /// <summary>
    /// Multiplier on how much plasma is released during supermatter reactions
    /// Default is ~1/750
    /// </summary>
    [ViewVariables(VVAccess.ReadOnly)]
    [DataField("plasmareleaseModifier")]
    public float PlasmaReleaseModifier = 0.001333f;

    /// <summary>
    /// Multiplier on how much oxygen is released during supermatter reactions.
    /// Default is ~1/325
    /// </summary>
    [ViewVariables(VVAccess.ReadOnly)]
    [DataField("oxygenreleaseModifier")]
    public float OxygenReleaseEfficiencyModifier = 0.0031f;

    #endregion SM Calculation

    #region SM Timer

    /// <summary>
    /// The point at which we should start sending messeges
    /// about the damage to the engi channels.
    /// </summary>
    [ViewVariables(VVAccess.ReadWrite)]
    [DataField("WarningPoint")]
    public const float WarningPoint = 50;

    /// <summary>
    /// The point at which we start sending messages to the common channel
    /// </summary>
    [ViewVariables(VVAccess.ReadWrite)]
    [DataField("emergencyPoint")]
    public const float EmergencyPoint = 500;

    /// <summary>
    /// we yell if over 50 damage every YellTimer Seconds
    /// </summary>
    [ViewVariables(VVAccess.ReadWrite)]
    public float YellTimer = 60f;

    /// <summary>
    /// set to YellTimer at first so it doesnt yell a minute after being hit
    /// </summary>
    [ViewVariables(VVAccess.ReadOnly)]
    public float YellAccumulator = 60f;

    /// <summary>
    ///     Timer for delam
    /// </summary>
    [ViewVariables(VVAccess.ReadOnly)]
    public float DelamTimerAccumulator;

    /// <summary>
    ///     Time until delam
    /// </summary>
    [ViewVariables(VVAccess.ReadWrite)]
    [DataField("delamTimer")]
    public float DelamTimer = 120f;

    /// <summary>
    ///     The message timer
    /// </summary>
    [ViewVariables(VVAccess.ReadWrite)]
    public float SpeakAccumulator = 60f;

    [ViewVariables(VVAccess.ReadOnly)]
    public float UpdateAccumulator = 0f;

    [ViewVariables(VVAccess.ReadWrite)]
    public float UpdateTimer = 1f;

    [ViewVariables(VVAccess.ReadOnly)]
    public float ZapAccumulator = 0f;

    [ViewVariables(VVAccess.ReadWrite)]
    public float ZapTimer = 10f;
    #endregion SM Timer

    #region SM Threshold

    /// <summary>
    /// Higher == Higher percentage of inhibitor gas needed
    /// before the charge inertia chain reaction effect starts.
    /// </summary>
    [ViewVariables(VVAccess.ReadOnly)]
    [DataField("powerlossinhibitiongasThreshold")]
    public float PowerlossInhibitionGasThreshold = 0.20f;

    /// <summary>
    /// Higher == More moles of the gas are needed before the charge
    /// inertia chain reaction effect starts.
    /// Scales powerloss inhibition down until this amount of moles is reached
    /// </summary>
    [ViewVariables(VVAccess.ReadOnly)]
    [DataField("powerlossinhibitionmoleThreshold")]
    public float PowerlossInhibitionMoleThreshold = 20f;

    /// <summary>
    /// bonus powerloss inhibition boost if this amount of moles is reached
    /// </summary>
    [ViewVariables(VVAccess.ReadOnly)]
    [DataField("powerlossinhibitionmoleboostThreshold")]
    public float PowerlossInhibitionMoleBoostThreshold = 500f;

    /// <summary>
    /// Above this value we can get lord singulo and independent mol damage,
    /// below it we can heal damage
    /// </summary>
    [ViewVariables(VVAccess.ReadOnly)]
    [DataField("molepenaltyThreshold")]
    public float MolePenaltyThreshold = 900f;

    /// <summary>
    /// The cutoff on power properly doing damage, pulling shit around,
    /// and delamming into a tesla. Low chance of pyro anomalies, +2 bolts of electricity
    /// </summary>
    [ViewVariables(VVAccess.ReadOnly)]
    [DataField("powerPenaltyThreshold")]
    public float PowerPenaltyThreshold = 2500f;

    /// <summary>
    /// Maximum safe operational temperature in degrees Celsius. Supermatter begins taking damage above this temperature.
    /// </summary>
    [ViewVariables(VVAccess.ReadOnly)]
    [DataField("heatpenaltyThreshold")]
    public float HeatPenaltyThreshold = 40f;

    /// <summary>
    /// is multiplied by ExplosionPoint to cap
    /// evironmental damage per cycle
    /// </summary>
    [ViewVariables(VVAccess.ReadOnly)]
    public float DamageHardcap = 0.002f;

    /// <summary>
    /// environmental damage is scaled by this
    /// </summary>
    [ViewVariables(VVAccess.ReadOnly)]
    [DataField("damageincreaseMultiplier")]
    public float DamageIncreaseMultiplier = 0.25f;

    /// <summary>
    /// if spaced sm wont take more than 2 damage per cycle
    /// </summary>
    [ViewVariables(VVAccess.ReadOnly)]
    [DataField("maxspaceexposureDamage")]
    public float MaxSpaceExposureDamage = 2;

    #endregion SM Threshold

    #region SM Delamm

    public bool DelamAnnounced = false;

    /// <summary>
    /// The point at which we delamm
    /// </summary>
    [ViewVariables(VVAccess.ReadOnly)]
    [DataField("explosionPoint")]
    public int DelaminationPoint = 900;

    //Are we delamming?
    [ViewVariables(VVAccess.ReadOnly)]
    public bool Delamming = false;

    //Explosion totalIntensity value
    [ViewVariables(VVAccess.ReadOnly)]
    [DataField("totalIntensity")]
    public float TotalIntensity = 50000f;

    //Explosion radius value
    [ViewVariables(VVAccess.ReadOnly)]
    [DataField("radius")]
    public float Radius = 50f;

    /// <summary>
    /// These would be what you would get at point blank, decreases with distance
    /// </summary>
    [ViewVariables(VVAccess.ReadOnly)]
    [DataField("detonationRads")]
    public float DetonationRads = 200f;

    #endregion SM Delamm

    #region SM Gas

    /// <summary>
    ///     Stores every gas fact
    /// </summary>
    /// <returns>
    ///     Given gasses:
    ///     <list type="bullet">
    ///     <item>
    ///     <c>RadMod</c>
    ///     <description>- radiation power modifier.</description>
    ///     </item>
    ///     <item>
    ///     <c>ZapMod</c>
    ///     <description>- tesla zap power modifier.</description>
    ///     </item>
    ///     <item>
    ///     <c>HeatMod</c>
    ///     <description>- modifier to crystal power gain from heat.</description>
    ///     </item>
    ///     <item>
    ///     <c>MoleMod</c>
    ///     <description>- produced gas mole count modifier.</description>
    ///     </item>
    ///     <item>
    ///     <c>HeatResistMod</c>
    ///     <description>- modifies threshold for crystal receiving heat damage.</description>
    ///     </item>
    ///     </list>
    /// </returns>
    /// <remarks>
    /// <para>RadMod has no /tg/ equivalents, however since SS14 meta is centered slightly more around rad collectors, this helps designs that rely on them instead of coils. Usually similar to ZapMod.</para>
    /// <para>ZapMod = "Power Transmission" on /tg/ wiki. High values will naturally create more powerful zaps.</para>
    /// <para>HeatMod = "Heat Power Gain" on /tg/ wiki. Makes SM get energy from temperature.</para>
    /// <para>MoleMod ~= "Gas Waste Multiplier" on /tg/ wiki. Temperature (not energy!) of produced gas depends on crystal energy instead.</para>
    /// <para>HeatResistMod = "Heat Resistance" on /tg/ wiki. Should never be so high as to shield from a trit fire.</para>
    /// <para>These values are for a 100% mix of such gas. These are additive, not multiplicative (so, 100%+mod)</para>
    /// </remarks>
    public static (float RadMod, float ZapMod, float HeatMod, float MoleMod, float HeatResistMod) GasDataFields(Gas? gas = null) => gas switch
    {
        // /tg/ values are an ok start, but definitely don't have to be adhered to.
        // Some values might seem extreme - completely intentional to encourage mixes.
        Gas.Oxygen => (0.8f, 0.4f, 1f, 0f, 0f), // Baby's first performance booster.
        Gas.Nitrogen => (0f, 0f, -1f, -2.5f, 0f), // Baseline. If SM doesn't work safely with 100% N2 something is wrong.
        Gas.CarbonDioxide => (0f, 0f, 1f, 1f, 0f), // Only useful for its special effect, decreasing power decay.
        Gas.Plasma => (2f, 1.5f, 1f, 19f, 0f), // Gives more power, and a lot more gases. 
        Gas.Tritium => (4f, 3f, 1f, 9f, 0f), // Go-to for massive power gains :)
        Gas.WaterVapor => (-0.25f, -0.25f, 1f, 11f, 0.25f), // Dangerous and useless. Or useless and dangerous?
        Gas.Frezon => (-3f, -3f, -1f, -9f, -0.5f), // Quick cooling, but won't save you at the last second due to heat mod. It's your fault ngl.
        Gas.Ammonia => (0f, 0f, .3f, 0f, 0f), // Another special effect, it's being consumed to give more power to the crystal.
        Gas.NitrousOxide => (0f, 0f, 0f, 0f, 5f), // Just gives heat resist
        _ => (0f, 0f, 0f, 0f, 0f)
    };

    #endregion SM Gas
    public float AmmoniaEnergyPerMole;
}

[Serializable, NetSerializable]
public sealed partial class SupermatterDoAfterEvent : SimpleDoAfterEvent
{

}
