using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Goobstation.Client.LinkAccount;

[GenerateTypedNameReferences]
public sealed partial class PatronPerksWindow : DefaultWindow
{
    public PatronPerksWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
