# SPDX-FileCopyrightText: 2025 Space Station 14 Contributors
#
# SPDX-License-Identifier: MIT-WIZARDS

- type: entity
  abstract: true
  parent: BasePartInorganic
  id: BasePart
  components:
  - type: Damageable
    damageContainer: OrganicPart # WoundMod Change
  # WoundMod START: Add the WoundMod component to track integrity/severing
  - type: WMBodyPart
    integrityThresholds:
      Healthy: 0
      Wounded: 10
      HeavilyWounded: 20
      CriticallyWounded: 40
      Dead: 50
    severIntegrity: 55
    enableIntegrity: 30
    minIntegrity: 0
    selfHealingAmount: 1
    healingTime: 15
  # WoundMod END
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTypeTrigger
        damageType: Blunt
        damage: 110
      behaviors:
      - !type:GibPartBehavior { }
    - trigger:
        !type:DamageTypeTrigger
        damageType: Slash
        damage: 150
      behaviors:
      - !type:GibPartBehavior { }
    - trigger:
        !type:DamageTypeTrigger
        damageType: Heat
        damage: 200
      behaviors:
      - !type:SpawnEntitiesBehavior
        spawnInContainer: true
        spawn:
          Ash:
            min: 1
            max: 1
      - !type:BurnBodyBehavior { }
      - !type:PlaySoundBehavior
        sound:
          collection: MeatLaserImpact
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: Fat
        Quantity: 3
      - ReagentId: Blood
        Quantity: 10
  - type: Tag # Goobstation
    tags:
    - Trash
    - Meat

# organic torsos have higher health
# this doesn't affect gibbing bodies as there is code to prevent torso gibbing while part of a body
- type: entity
  abstract: true
  parent: BaseTorsoInorganic
  id: BaseTorso
  components:
  # WoundMod START: Torsos are much harder to destroy/sever
  - type: WMBodyPart
    integrityThresholds:
      Healthy: 0
      Wounded: 50
      HeavilyWounded: 100
      CriticallyWounded: 150
      Dead: 200
    severIntegrity: 1000 # Effectively impossible to sever via damage alone
    enableIntegrity: 150
    minIntegrity: 0
    selfHealingAmount: 2
    healingTime: 10
  # WoundMod END
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTypeTrigger
        damageType: Blunt
        damage: 400
      behaviors:
      - !type:GibPartBehavior { }
    - trigger:
        !type:DamageTypeTrigger
        damageType: Slash
        damage: 400
      behaviors:
      - !type:GibPartBehavior { }
    - trigger:
        !type:DamageTypeTrigger
        damageType: Heat
        damage: 400
      behaviors:
      - !type:SpawnEntitiesBehavior
        spawnInContainer: true
        spawn:
          Ash:
            min: 1
            max: 1
      - !type:BurnBodyBehavior { }
      - !type:PlaySoundBehavior
        sound:
          collection: MeatLaserImpact
  - type: Extractable # torso is meatier
    juiceSolution:
      reagents:
      - ReagentId: Fat
        Quantity: 10
      - ReagentId: Blood
        Quantity: 20
